[package]
name = "pahkat-server"
version = "0.6.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
pahkat-types = { path = "../pahkat-types" }
pahkat-common = { path = "../pahkat-common" }
clap = { version = "2.33.0" }
diesel = { version = "1.4.2", features = ["sqlite", "chrono", "r2d2"] }
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"
actix-web = "1.0.0-beta.5"
actix = "0.8.2"
glob = "0.3.0"
log = "0.4.6"
env_logger = "0.6.1"
chrono = "0.4.6"
uuid = { version = "0.7.4", features = ["serde", "v4"] }
failure = "0.1.5"
directories = "2.0.0"
