[package]
name = "pahkat-server"
version = "0.6.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
pahkat-types = { path = "../pahkat-types" }
pahkat-common = { path = "../pahkat-common" }
clap = { version = "2.33.0" }
actix-web = "1.0.0-beta.3"
actix = "0.8"
glob = "0.3.0"
log = "0.4.6"
env_logger = "0.6"
