[package]
name = "pahkat-client"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

# [lib]
# crate-type = ["staticlib"]

[[bin]]
name = "pahkatc"
path = "src/bin/pahkatc.rs"
required-features = ["binaries"]

[dependencies]
pahkat = { git = "https://github.com/divvun/pahkat", branch = "master" }
reqwest = "0.9.5"
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
semver = "0.9.0"
tempdir = "0.3.7"
url = "1.7.2"
libc = "0.2.43"
rust-crypto = "0.2.36"
lazy_static = "1.2.0"
sentry = "0.12.0"
maplit = "1.0"
dirs = "1.0"

# Prefix feature
rhai = { version = "0.8", optional = true }
xz2 = { version = "*", optional = true }
rusqlite = { version = "*", features = ["bundled"], optional = true }
tar = { version = "*", optional = true }

# Binaries feature
clap = { version = "2.32.0", optional = true }
termcolor = { version = "0.3", optional = true }

# IPC feature
jsonrpc-core = { version = "9", optional = true }
jsonrpc-macros = { version = "9", optional = true }
jsonrpc-pubsub = { version = "9", optional = true }

# MacOS-specific
[target.'cfg(target_os="macos")'.dependencies]
plist = { version = "0.3.0" }

# Windows-specific
[target.'cfg(target_os="windows")'.dependencies]
winapi = { version = "0.3", features = ["shellapi"] }
winreg = { git = "https://github.com/bbqsrc/winreg-rs", branch = "master" }

[features]
prefix = ["rhai", "tar", "xz2", "rusqlite"]
ipc = ["jsonrpc-core", "jsonrpc-macros", "jsonrpc-pubsub"]
binaries = ["clap", "termcolor"]
