[package]
name = "bahkat"
version = "0.3.1"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]

[[bin]]
name = "bahkat"
path = "src/main.rs"
required-features = ["binaries"]

[dependencies]
clap = { version = "*", optional = true }
termcolor = { version = "0.3", optional = true }
pathdiff = { version = "0.1", optional = true }
serde = "*"
serde_derive = "*"
serde_json = "*"

[features]
binaries = ["clap", "termcolor", "pathdiff"]