[package]
name = "pahkat-client"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]

[[bin]]
name = "pahkatc"
path = "src/main.rs"
required-features = ["binaries"]

[dependencies]
pahkat = { git = "https://github.com/divvun/pahkat", branch = "feature/macos" }
rusqlite = "*"
reqwest = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
semver = "0.9.0"
tar = "*"
xz2 = "*"
tempdir = "*"
url = "*"
rhai = "0.8.1"
winreg = { git = "https://github.com/bbqsrc/winreg-rs", branch = "master" }
clap = { version = "*", optional = true }
termcolor = { version = "0.3", optional = true }
jsonrpc-core = { version = "*", optional = true }
jsonrpc-macros = { version = "*", optional = true }
jsonrpc-pubsub = { version = "*", optional = true }
jsonrpc-tcp-server = { version = "*", optional = true }

[features]
ipc = ["jsonrpc-core", "jsonrpc-macros", "jsonrpc-pubsub", "jsonrpc-tcp-server"]
binaries = ["clap", "termcolor"]