[package]
name = "pahkat-client"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]

# [lib]
# crate-type = ["staticlib"]

[[bin]]
name = "pahkatc"
path = "src/bin/pahkatc.rs"
required-features = ["binaries"]

[dependencies]
pahkat = { git = "https://github.com/divvun/pahkat", branch = "master" }
rusqlite = "*"
reqwest = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
semver = "0.9.0"
tar = "*"
xz2 = "*"
tempdir = "*"
url = "*"
rhai = "0.8.1"
libc = "*"
rust-crypto = "^0.2"
lazy_static = "1.0"
sentry = { path = "../sentry-rust", branch = "master" }
maplit = "1.0"

# Windows-specific
winreg = { git = "https://github.com/bbqsrc/winreg-rs", branch = "master" }

# MacOS-specific
[target.'cfg(target_os="macos")'.dependencies]
plist = { version = "0.2" }

# Binaries feature
clap = { version = "*", optional = true }
termcolor = { version = "0.3", optional = true }

# IPC feature
jsonrpc-core = { version = "*", optional = true }
jsonrpc-macros = { version = "*", optional = true }
jsonrpc-pubsub = { version = "*", optional = true }
jsonrpc-tcp-server = { version = "*", optional = true }

[features]
ipc = ["jsonrpc-core", "jsonrpc-macros", "jsonrpc-pubsub", "jsonrpc-tcp-server"]
binaries = ["clap", "termcolor"]