[package]
name = "pahkat-client"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "dylib", "rlib"]

[[bin]]
name = "pahkatc"
path = "src/bin/pahkatc.rs"
required-features = ["binaries"]

[dependencies]
pahkat-types = { git = "https://github.com/divvun/pahkat", branch = "develop" }
reqwest = "0.9.18"
serde = "1.0.94"
serde_json = "1.0.40"
serde_derive = "1.0.94"
semver = "0.9.0"
tempdir = "0.3.7"
url = "1.7.2"
url_serde = "0.2.0"
libc = "0.2.58"
rust-crypto = "0.2.36"
lazy_static = "1.3.0"
sentry = "0.15.5"
maplit = "1.0"
dirs = "2.0.1"
crossbeam = "0.7.1"
directories = "2.0.1"
chrono = "0.4.7"
hashbrown = { version = "0.5.0", features = ["serde"] }
is_executable = "0.1.2"

# Prefix feature
rhai = { version = "0.9", optional = true }
xz2 = { version = "0.1.6", optional = true }
rusqlite = { version = "0.19.0", features = ["bundled"], optional = true }
tar = { version = "0.4.26", optional = true }

# Binaries feature
clap = { version = "2.33.0", optional = true }
termcolor = { version = "1.0.5", optional = true }
indicatif = { version = "0.11.0", optional = true }

# MacOS-specific
[target.'cfg(target_os="macos")'.dependencies]
plist = { version = "0.4.2" }

# Windows-specific
[target.'cfg(target_os="windows")'.dependencies]
winapi = { version = "0.3", features = ["shellapi"] }
winreg = { git = "https://github.com/bbqsrc/winreg-rs", branch = "master" }

[features]
prefix = ["rhai", "tar", "xz2", "rusqlite"]
binaries = ["clap", "termcolor", "indicatif"]
