[package]
name = "pahkat-client"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]

[[bin]]
name = "pahkatc"
path = "src/main.rs"
required-features = ["binaries"]

[dependencies]
pahkat = { git = "https://github.com/bbqsrc/pahkat", branch = "master" }
rusqlite = "*"
reqwest = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
semver = "0.9.0"
tar = "*"
xz2 = "*"
tempdir = "*"
url = "*"
rhai = "0.8.1"
clap = { version = "*", optional = true }
termcolor = { version = "0.3", optional = true }

[features]
binaries = ["clap", "termcolor"]