[package]
name = "pahkat-client"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]

# [lib]
# crate-type = ["staticlib"]

[[bin]]
name = "pahkatc"
path = "src/bin/pahkatc.rs"
required-features = ["binaries"]

[dependencies]
pahkat = { path = "../bahkat", branch = "master" }
# pahkat = { git = "https://github.com/divvun/pahkat", branch = "master" }
reqwest = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
semver = "0.9.0"
tempdir = "*"
url = "*"
libc = "*"
rust-crypto = "^0.2"
lazy_static = "1.0"
sentry = { path = "../sentry-rust", branch = "master" }
maplit = "1.0"

# Prefix feature
rhai = { version = "0.8", optional = true }
xz2 = { version = "*", optional = true }
rusqlite = { version = "*", features = ["bundled"], optional = true }
tar = { version = "*", optional = true }

# Binaries feature
clap = { version = "*", optional = true }
termcolor = { version = "0.3", optional = true }

# IPC feature
jsonrpc-core = { version = "*", optional = true }
jsonrpc-macros = { version = "*", optional = true }
jsonrpc-pubsub = { version = "*", optional = true }

# MacOS-specific
[target.'cfg(target_os="macos")'.dependencies]
plist = { version = "0.2" }

# Windows-specific
[target.'cfg(target_os="windows")'.dependencies]
winapi = { version = "0.3", features = ["shellapi"] }
winreg = { git = "https://github.com/bbqsrc/winreg-rs", branch = "master" }

[features]
prefix = ["rhai", "tar", "xz2", "rusqlite"]
ipc = ["jsonrpc-core", "jsonrpc-macros", "jsonrpc-pubsub"]
binaries = ["clap", "termcolor"]