[package]
name = "pahkat-common"
version = "0.6.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
pahkat-types = { path = "../pahkat-types" }
serde = "1.0.91"
serde_json = "1.0.39"
pathdiff = { version = "0.1" }
